 version: '3'

 services:
   frontend:
     container_name: dogblog_frontend
     hostname: dogblog_frontend
     build: "frontend/"
     command: sh /code/frontend/entrypoint.sh
     working_dir: /code/frontend
     env_file: .env
     ports:
       - 8080:8080
     volumes:
       - ./frontend:/code/frontend
       - ./frontend/node_modules:/code/frontend/node_modules
     ulimits:
       nofile:
         soft: 10240
         hard: 10240
   db:
     container_name: dogblog_db
     hostname: dogblog_db
     build: "deploy/docker/postgres/"
     env_file: .env
     volumes:
       - pgdata:/var/lib/postgresql/data/ # Preserves db between runs.
     ports:
       - 5432
   backend:
     container_name: dogblog_backend
     hostname: dogblog_backend
     build: .
     command: sh /code/backend/entrypoint.sh
     entrypoint: sh /code/deploy/docker/postgres/wait-for-postgres.sh
     volumes:
       - .:/code
     env_file: .env
     ports:
       - 8000:8000
     links:
       - db
       - frontend
     depends_on:
       - db
       - frontend
 volumes:
     backend:
     frontend:
     pgdata:

